
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (1, 'SAMURAIの宿', 'house01.jpg', '北海道の大自然を満喫できるログハウス風の宿。冬は一面の雪景色が広がり、スキーリゾートへのアクセスも良好です。', 6500, 4, '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (2, 'ペンション SAMURAI', 'house02.jpg', '青森の新鮮な海の幸と郷土料理が自慢のペンション。木の温もりを感じるアットホームな空間でおくつろぎください。', 7000, 3, '030-0945', '青森県青森市桜川X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (3, 'SAMURAI荘', 'house03.jpg', '最寄り駅から徒歩5分以内！ビジネスや一人旅にも使いやすい好立地。Wi-Fi完備でテレワークにもおすすめです。', 4800, 2, '029-5618', '岩手県和賀郡西和賀町沢内両沢X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (4, 'ゲストハウス SAMURAI', 'house04.jpg', '世界中の旅人が集まる活気あるゲストハウス。共有ラウンジでは毎晩交流会が開催されています。自炊キッチン完備。', 3500, 6, '989-0555', '宮城県刈田郡七ヶ宿町滝ノ上X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (5, 'SAMURAI屋', 'house05.jpg', '天然温泉掛け流しの露天風呂が楽しめる和風旅館。きりたんぽ鍋など、秋田の味覚を存分に味わえるプランが人気です。', 12000, 4, '018-2661', '秋田県山本郡八峰町八森浜田X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (6, '民宿 SAMURAI', 'house06.jpg', 'のどかな田園風景に囲まれた農家民宿。自家製の無農薬野菜を使った手作り朝食が大好評。ペットの同伴も可能です。', 4500, 3, '999-6708', '山形県酒田市泉興野X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (7, 'SAMURAIハイツ', 'house07.jpg', '磐梯山の麓に位置するリゾートハイツ。夏は避暑地として、冬はスノースポーツの拠点として一年中楽しめます。', 6500, 4, '969-5147', '福島県会津若松市大戸町芦牧X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (8, 'メゾンSAMURAI', 'house08.jpg', '駅からのアクセス抜群。全室シモンズ製ベッドを導入しており、快適な睡眠をお約束します。周辺に飲食店多数あり。', 4900, 2, '310-0021', '茨城県水戸市南町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (9, 'SAMURAIマンション', 'house09.jpg', '観光の拠点に最適。マンションタイプの広々としたお部屋で、グループや家族連れでもゆったり過ごせます。', 8500, 5, '323-1101', '栃木県下都賀郡藤岡町大前X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (10, 'コーポSAMURAI', 'house10.jpg', '温泉街まで車でスグ！和洋折衷のモダンなお部屋が特徴です。無料の貸切風呂でプライベートな時間を満喫できます。', 9000, 4, '370-0806', '群馬県高崎市上和田町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (11, 'SAMURAIハイム', 'house01.jpg', 'レトロな街並みまで徒歩圏内。歴史を感じる洋館風の造りで、女性グループやカップルに大人気のおしゃれな空間です。', 6000, 2, '344-0125', '埼玉県春日部市飯沼X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (12, 'ヴィラSAMURAI', 'house02.jpg', 'テーマパークへの無料シャトルバス運行中！海風を感じるオーシャンビューの客室でリゾート気分を楽しめます。', 4500, 3, '272-0011', '千葉県市川市高谷新町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (13, 'SAMURAIパレス', 'house03.jpg', '東京の夜景を一望できるラグジュアリーな宿泊施設。都会の喧騒を忘れさせる、洗練された大人の隠れ家です。', 15000, 2, '130-0023', '東京都墨田区立川X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (14, 'ロッジ SAMURAI', 'house04.jpg', '森にひっそりと佇むプライベートロッジ。全室に専用の露天風呂が付いており、贅沢な非日常を体験できます。', 18000, 4, '240-0006', '神奈川県横浜市保土ヶ谷区星川X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (15, 'SAMURAI館', 'house05.jpg', '日本海の新鮮な魚介と、美味しい地元のお米を堪能できる美食の宿。冬場はしんしんと降る雪見酒も楽しめます。', 8800, 4, '950-0201', '新潟県新潟市駒込X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (16, 'SAMURAI山荘', 'house06.jpg', 'アルペンルートの入り口に位置する山荘。登山客や写真家に愛される、シンプルで清潔感のあるリーズナブルなお宿です。', 4500, 2, '939-8155', '富山県富山市江本X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (17, 'SAMURAIの家', 'house07.jpg', '古い町並みに近い古民家をリノベーションした一棟貸しの宿。伝統工芸の美しさを随所に感じられます。', 11000, 6, '929-0111', '石川県能美市吉原町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (18, '侍の宿', 'house08.jpg', '冬の味覚の王様・カニが食べられる冬季限定プランが大人気。目の前に美しい海が広がる絶好のロケーションです。', 13000, 4, '910-2354', '福井県福井市東天田町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (19, 'ペンション 侍', 'house09.jpg', '客室から富士山を独り占め！湖畔に建つヨーロピアン調の可愛らしいペンションです。オーナーの手作りケーキ付き。', 7500, 3, '403-0003', '山梨県富士吉田市大明見X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (20, '侍荘', 'house10.jpg', '満天の星空が楽しめる標高1000mの高原リゾート。夏は涼しく快適に過ごせます。無料の天体観測ツアーあり。', 6800, 4, '395-0017', '長野県飯田市東新町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (21, 'ゲストハウス 侍', 'house01.jpg', '古い町並みに溶け込むレトロなゲストハウス。縁側でのんびりお茶を飲みながら、旅の疲れを癒せます。外国語対応可。', 3800, 8, '509-5147', '岐阜県土岐市泉郷町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (22, '侍屋', 'house02.jpg', '美しいビーチまで徒歩1分！マリンスポーツや釣りを満喫したい若者に大人気の、カジュアルでお財布に優しいお宿です。', 4200, 4, '434-0002', '静岡県浜松市尾野X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (23, '民宿 侍', 'house03.jpg', 'ご当地グルメが食べられるボリューム満点の夕食プランあり。出張のビジネスマンにも嬉しい広々とした大浴場を完備。', 5500, 2, '444-3261', '愛知県豊田市東大林町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (24, '侍ハイツ', 'house04.jpg', '有名神社への参拝にとても便利。館内はすべて畳敷きになっており、ハイハイする小さなお子様連れでも安心です。', 7200, 5, '510-0201', '三重県鈴鹿市稲生町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (25, 'メゾン侍', 'house05.jpg', '目の前は雄大な湖！サイクリスト向けの自転車持ち込みOKな特別ルームや、メンテナンススペースを完備しています。', 6500, 3, '520-2353', '滋賀県野洲市久野部X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (26, '侍マンション', 'house06.jpg', '京都観光の中心地まで徒歩圏内。和モダンなインテリアで統一され、長期滞在でも暮らすようにゆったりと滞在できます。', 4900, 2, '612-8369', '京都府京都市伏見区村上町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (27, 'コーポ侍', 'house07.jpg', 'テーマパークまで電車でスグの超好立地！お部屋でたこ焼きパーティーができる専用ホットプレートの無料貸出あり。', 5800, 4, '578-0915', '大阪府東大阪市古箕輪X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (28, '侍ハイム', 'house08.jpg', '有名な名湯を引いた贅沢な温泉宿。最高級の和牛ステーキディナーで、記念日などの至福のひとときをお過ごしください。', 14000, 2, '655-0891', '兵庫県神戸市垂水区山手X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (29, 'ヴィラ侍', 'house09.jpg', '野生の鹿が遊びに来ることもある自然豊かな環境。歴史あるお寺や神社への、清々しい早朝散歩がおすすめです。', 6200, 4, '630-1126', '奈良県奈良市法用町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (30, '侍パレス', 'house10.jpg', '美しい海を見下ろす高台に建つリゾートホテル。夕日が映えるインフィニティプールと本格スパで最高のリラクゼーションを。', 16000, 2, '640-8319', '和歌山県和歌山市手平X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (31, 'ロッジ 侍', 'house01.jpg', '広大な砂丘のすぐそば！星空保護区に指定された美しい夜空を寝袋で体験できる、手ぶらグランピングプランが人気。', 4800, 4, '689-2203', '鳥取県東伯郡北栄町原X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (32, '侍館', 'house02.jpg', '有名な大社へのアクセス抜群。縁結びの一人旅を応援する、セキュリティ万全の女性専用フロアと充実したアメニティを完備。', 5400, 2, '694-0035', '島根県大田市五十猛町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (33, '侍山荘', 'house03.jpg', '白壁の町並みに調和する、江戸時代の蔵を美しく改装した隠れ家宿。タイムスリップしたかのような体験が待っています。', 9500, 4, '712-8036', '岡山県倉敷市水島西弥生町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (34, '侍の家', 'house04.jpg', '世界遺産の島へ向かうフェリー乗り場まで徒歩5分。瀬戸内海の穏やかな海を眺めながら、名物カキフライをご堪能ください。', 6000, 3, '726-0011', '広島県府中市広谷町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (35, 'さむらいの宿', 'house05.jpg', '城下町の散策に最適。幕末の志士たちが通ったとされる歴史ある通りに面しており、窓からは風情ある景色を楽しめます。', 6600, 4, '750-0451', '山口県下関市豊田町阿座上X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (36, 'ペンション さむらい', 'house06.jpg', '最寄り駅から徒歩5分以内。激流を下るラフティングなど、大自然を満喫するアクティブな旅行の拠点にぴったりの宿。', 4000, 4, '778-0004', '徳島県三好市池田町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (37, 'さむらい荘', 'house07.jpg', '本場のうどん名店巡りに便利な立地。館主が直接教える、アットホームな「手打ちうどん体験教室（要予約）」が大好評です。', 5200, 3, '762-0067', '香川県坂出市瀬居町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (38, 'ゲストハウス さむらい', 'house08.jpg', '有名な温泉本館まで下駄を鳴らして歩いて行ける距離。ロビーにはみかんジュース蛇口があり、宿泊者同士の交流も盛んです。', 3200, 6, '792-0828', '愛媛県新居浜市松原町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (39, 'さむらい屋', 'house09.jpg', '幕末の偉人ゆかりの地。毎晩、カツオのタタキを豪快に炙る実演ショーがあり、美味しい地酒と共にワイワイ楽しめます。', 7800, 5, '787-1323', '高知県四万十市西土佐中半X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (40, '民宿 さむらい', 'house10.jpg', '賑やかな屋台街まで徒歩圏内で、ご当地グルメを深夜まで大満喫！朝食は辛子明太子と特製スープのセットをご用意。', 5000, 2, '835-0018', '福岡県みやま市瀬高町高柳X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (41, 'さむらいハイツ', 'house01.jpg', '伝統的な焼き物の窯元巡りに。お食事は全て美しい器で提供され、目でも舌でも楽しめるリーズナブルなお宿です。', 4500, 2, '840-0213', '佐賀県佐賀市大和町久留間X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (42, 'メゾンさむらい', 'house02.jpg', '異国情緒あふれる港町の夜景を、全てのお部屋から見下ろすことができます。手作りカステラとお茶のウェルカムサービスあり。', 8200, 3, '852-8104', '長崎県長崎市茂里町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (43, 'さむらいマンション', 'house03.jpg', '雄大なカルデラ地形を望む大自然のロケーション。自家牧場の絞りたて牛乳で作った濃厚ソフトクリームが絶品です。', 6800, 4, '863-0021', '熊本県天草市港町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (44, 'コーポさむらい', 'house04.jpg', '県内屈指の温泉街へのアクセスが良好。泥湯や砂むし風呂など、ユニークでデトックス効果抜群の温泉体験が待っています。', 5500, 4, '872-0014', '大分県宇佐市南鶴田新田X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (45, 'さむらいハイム', 'house05.jpg', '南国気分を味わえるヤシの木に囲まれたリゾート。チキン南蛮と地元産完熟マンゴーを使った朝食ビュッフェが自慢です。', 7500, 4, '880-0947', '宮崎県宮崎市薫る坂X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (46, 'ヴィラさむらい', 'house06.jpg', '活火山の力強い姿を真正面に捉えるオーシャンビューヴィラ。名産の黒豚しゃぶしゃぶと本格芋焼酎で至高の夜を。', 4800, 2, '895-2103', '鹿児島県薩摩郡さつま町紫尾X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (47, 'さむらいパレス', 'house07.jpg', 'エメラルドグリーンのプライベートビーチ直結！三線の生ライブを聴きながら、冷えた地ビールで乾杯しましょう。', 12000, 4, '904-2165', '沖縄県沖縄市宮里X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (48, 'ロッジ さむらい', 'house08.jpg', '函館の100万ドルの夜景を一望できる丘の上のロッジ。冬は暖炉の火を眺めながら、静かでロマンチックな時間を過ごせます。', 8500, 2, '041-1121', '北海道亀田郡七飯町大中山X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (49, 'さむらい館', 'house09.jpg', '人気の動物園へのアクセス抜群！キッズスペースやファミリー向け大型ルーム完備で、小さなお子様連れに優しいお宿です。', 6000, 5, '095-0019', '北海道士別市大通東X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (50, 'さむらい山荘', 'house10.jpg', 'オホーツク海の流氷観光に最適。冷えた体を芯から温める天然温泉と、カニやイクラが山盛りの豪華海鮮丼が自慢。', 9500, 4, '099-0423', '北海道紋別郡遠軽町若松X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (51, 'さむらいの家', 'house01.jpg', '十勝平野の広大な農場の中にあるファームステイ型の宿。乗馬体験やトラクターツアーなど、北海道ならではの体験を。', 7000, 4, '089-0533', '北海道中川郡幕別町札内新北町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (52, 'サムライの宿', 'house02.jpg', '極上のパウダースノーを目当てに世界中からスキーヤーが集まる宿。リフト券付きのお得な連泊プランをご用意しています。', 4800, 3, '049-3514', '北海道山越郡長万部町富野X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (53, 'ペンション サムライ', 'house03.jpg', '新千歳空港から車で15分。早朝フライトの前泊や、北海道旅行の最終日の拠点として非常に便利な、コスパ最強の立地です。', 5000, 2, '066-0018', '北海道千歳市旭ヶ丘X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (54, 'サムライ荘', 'house04.jpg', '札幌・大通公園に近く、雪まつりやイベント参加に絶好のロケーション。清潔感のあるカプセルタイプで一人旅に最適。', 3500, 1, '003-0804', '北海道札幌市白石区菊水四条X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (55, 'ゲストハウス サムライ', 'house05.jpg', '小樽のレトロな運河沿いにあるゲストハウス。1階はお洒落なカフェバーになっており、地元の人との交流も楽しめます。', 3800, 6, '042-0908', '北海道函館市銅山町X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (56, 'サムライ屋', 'house06.jpg', '名湯の地獄谷から引いた濃厚な硫黄泉が自慢。豊かな自然に囲まれ、四季折々の雪景色を楽しみながら湯浴みを。', 11000, 4, '050-0061', '北海道室蘭市八丁平X-XX-XX', '012-345-678');
INSERT IGNORE INTO houses (id, name, image_name, description, price, capacity, postal_code, address, phone_number) VALUES (57, '民宿 サムライ', 'house07.jpg', '知床の大自然をガイドするネイチャーツアー付きプランが人気。運が良ければキタキツネやエゾシカとの出会いが待っています。', 6500, 3, '059-0027', '北海道登別市青葉町X-XX-XX', '012-345-678');

-- rolesテーブル
INSERT IGNORE INTO roles (id, name) VALUES (1, 'ROLE_GENERAL');
INSERT IGNORE INTO roles (id, name) VALUES (2, 'ROLE_ADMIN');

-- usersテーブル
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (1, '侍 太郎', 'サムライ タロウ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'taro.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 1, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (2, '侍 花子', 'サムライ ハナコ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'hanako.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 2, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (3, '侍 義勝', 'サムライ ヨシカツ', '638-0644', '奈良県五條市西吉野町湯川X-XX-XX', '090-1234-5678', 'yoshikatsu.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (4, '侍 幸美', 'サムライ サチミ', '342-0006', '埼玉県吉川市南広島X-XX-XX', '090-1234-5678', 'sachimi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (5, '侍 雅', 'サムライ ミヤビ', '527-0209', '滋賀県東近江市佐目町X-XX-XX', '090-1234-5678', 'miyabi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (6, '侍 正保', 'サムライ マサヤス', '989-1203', '宮城県柴田郡大河原町旭町X-XX-XX', '090-1234-5678', 'masayasu.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (7, '侍 真由美', 'サムライ マユミ', '951-8015', '新潟県新潟市松岡町X-XX-XX', '090-1234-5678', 'mayumi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (8, '侍 安民', 'サムライ ヤスタミ', '241-0033', '神奈川県横浜市旭区今川町X-XX-XX', '090-1234-5678', 'yasutami.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (9, '侍 章緒', 'サムライ アキオ', '739-2103', '広島県東広島市高屋町宮領X-XX-XX', '090-1234-5678', 'akio.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (10, '侍 祐子', 'サムライ ユウコ', '601-0761', '京都府南丹市美山町高野X-XX-XX', '090-1234-5678', 'yuko.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (11, '侍 秋美', 'サムライ アキミ', '606-8235', '京都府京都市左京区田中西春菜町X-XX-XX', '090-1234-5678', 'akimi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (12, '侍 信平', 'サムライ シンペイ', '673-1324', '兵庫県加東市新定X-XX-XX', '090-1234-5678', 'shinpei.samurai@example.com', 'password', 1, false);


-- reservationsテーブル
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (1, 1, 1, '2023-04-01', '2023-04-02', 2, 6000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (2, 2, 1, '2023-04-01', '2023-04-02', 3, 7000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (3, 3, 1, '2023-04-01', '2023-04-02', 4, 8000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (4, 4, 1, '2023-04-01', '2023-04-02', 5, 9000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (5, 5, 1, '2023-04-01', '2023-04-02', 6, 10000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (6, 6, 1, '2023-04-01', '2023-04-02', 2, 6000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (7, 7, 1, '2023-04-01', '2023-04-02', 3, 7000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (8, 8, 1, '2023-04-01', '2023-04-02', 4, 8000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (9, 9, 1, '2023-04-01', '2023-04-02', 5, 9000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (10, 10, 1, '2023-04-01', '2023-04-02', 6, 10000);
INSERT IGNORE INTO reservations (id, house_id, user_id, checkin_date, checkout_date, number_of_people, amount) VALUES (11, 11, 1, '2023-04-01', '2023-04-02', 2, 6000);

-- ▼一番最後にこの1行を追記する
UPDATE houses SET reservation_count = (SELECT COUNT(id) FROM reservations WHERE reservations.house_id = houses.id);

